//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Macros {
    
    private MacrosMacro[] macroField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Macro")]
    public MacrosMacro[] Macro {
        get {
            return this.macroField;
        }
        set {
            this.macroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
public partial class MacrosMacro {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class RuleType {
    
    private OptionType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Option")]
    public OptionType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum OptionType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Allowed:Prerelease Signers")]
    AllowedPrereleaseSigners,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Allowed:Kits Signers")]
    AllowedKitsSigners,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:UMCI")]
    EnabledUMCI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disabled:Winload Driver Signature Enforcement Menu")]
    DisabledWinloadDriverSignatureEnforcementMenu,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:UMCI Debug Options")]
    EnabledUMCIDebugOptions,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:UMCI Cache Data Volumes")]
    EnabledUMCICacheDataVolumes,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Allowed:SeQuerySigningPolicy Extension")]
    AllowedSeQuerySigningPolicyExtension,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Required:WHQL")]
    RequiredWHQL,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:Filter Edited Boot Options")]
    EnabledFilterEditedBootOptions,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disabled:UMCI USN 0 Protection")]
    DisabledUMCIUSN0Protection,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disabled:Winload Debugging Mode Menu")]
    DisabledWinloadDebuggingModeMenu,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 11")]
    Bit11,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 12")]
    Bit12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 13")]
    Bit13,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:UMCI Trust USN 0")]
    EnabledUMCITrustUSN0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 15")]
    Bit15,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 16")]
    Bit16,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 17")]
    Bit17,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 18")]
    Bit18,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bit 19")]
    Bit19,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Enabled:Flight Signing")]
    EnabledFlightSigning,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Ignored:Flight Signing EKU")]
    IgnoredFlightSigningEKU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class Strings {
    
    private string[] stringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("String")]
    public string[] String {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class QWordArrayType {
    
    private ulong defaultField;
    
    private ulong[] valuesField;
    
    /// <remarks/>
    public ulong Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable=false)]
    public ulong[] Values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class QWordRangeType {
    
    private ulong defaultField;
    
    private ulong lowerBoundField;
    
    private ulong upperBoundField;
    
    /// <remarks/>
    public ulong Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    public ulong LowerBound {
        get {
            return this.lowerBoundField;
        }
        set {
            this.lowerBoundField = value;
        }
    }
    
    /// <remarks/>
    public ulong UpperBound {
        get {
            return this.upperBoundField;
        }
        set {
            this.upperBoundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class DWordArrayType {
    
    private uint defaultField;
    
    private uint[] valuesField;
    
    /// <remarks/>
    public uint Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Value", IsNullable=false)]
    public uint[] Values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class DWordRangeType {
    
    private uint defaultField;
    
    private uint lowerBoundField;
    
    private uint upperBoundField;
    
    /// <remarks/>
    public uint Default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    public uint LowerBound {
        get {
            return this.lowerBoundField;
        }
        set {
            this.lowerBoundField = value;
        }
    }
    
    /// <remarks/>
    public uint UpperBound {
        get {
            return this.upperBoundField;
        }
        set {
            this.upperBoundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public partial class SettingValueType {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Binary", typeof(byte[]), DataType="hexBinary")]
    [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("DWord", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("DWordChoice", typeof(DWordArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("DWordRange", typeof(DWordRangeType))]
    [System.Xml.Serialization.XmlElementAttribute("MultiString", typeof(Strings))]
    [System.Xml.Serialization.XmlElementAttribute("Option", typeof(BcdRuleOptionType))]
    [System.Xml.Serialization.XmlElementAttribute("QWord", typeof(ulong))]
    [System.Xml.Serialization.XmlElementAttribute("QWordChoice", typeof(QWordArrayType))]
    [System.Xml.Serialization.XmlElementAttribute("QWordRange", typeof(QWordRangeType))]
    [System.Xml.Serialization.XmlElementAttribute("String", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum BcdRuleOptionType {
    
    /// <remarks/>
    Ignored,
    
    /// <remarks/>
    Enforced,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class BcdRule {
    
    private SettingValueType valueField;
    
    private BcdObjectType objectField;
    
    private string elementField;
    
    private bool requiresBitLockerWithTPMField;
    
    private bool requiresBitLockerWithTPMFieldSpecified;
    
    private bool requiresVBSField;
    
    private bool requiresVBSFieldSpecified;
    
    /// <remarks/>
    public SettingValueType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public BcdObjectType Object {
        get {
            return this.objectField;
        }
        set {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Element {
        get {
            return this.elementField;
        }
        set {
            this.elementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RequiresBitLockerWithTPM {
        get {
            return this.requiresBitLockerWithTPMField;
        }
        set {
            this.requiresBitLockerWithTPMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresBitLockerWithTPMSpecified {
        get {
            return this.requiresBitLockerWithTPMFieldSpecified;
        }
        set {
            this.requiresBitLockerWithTPMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool RequiresVBS {
        get {
            return this.requiresVBSField;
        }
        set {
            this.requiresVBSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RequiresVBSSpecified {
        get {
            return this.requiresVBSFieldSpecified;
        }
        set {
            this.requiresVBSFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum BcdObjectType {
    
    /// <remarks/>
    Any,
    
    /// <remarks/>
    bootmgr,
    
    /// <remarks/>
    osloader,
    
    /// <remarks/>
    resume,
    
    /// <remarks/>
    memdiag,
    
    /// <remarks/>
    ntldr,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class BcdRules {
    
    private BcdRule[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BcdRule")]
    public BcdRule[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Setting {
    
    private SettingValueType valueField;
    
    private string keyField;
    
    private string valueNameField;
    
    /// <remarks/>
    public SettingValueType Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Settings {
    
    private Setting[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Setting")]
    public Setting[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CertEKU {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CertOemID {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CertPublisher {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CertIssuer {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CertRoot {
    
    private CertEnumType typeField;
    
    private byte[] valueField;
    
    private ushort tbsHashAlgorithmField;
    
    private bool tbsHashAlgorithmFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public CertEnumType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort TbsHashAlgorithm {
        get {
            return this.tbsHashAlgorithmField;
        }
        set {
            this.tbsHashAlgorithmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TbsHashAlgorithmSpecified {
        get {
            return this.tbsHashAlgorithmFieldSpecified;
        }
        set {
            this.tbsHashAlgorithmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum CertEnumType {
    
    /// <remarks/>
    TBS,
    
    /// <remarks/>
    Wellknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class FileRulesRef {
    
    private FileRuleRef[] fileRuleRefField;
    
    private string workaroundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileRuleRef")]
    public FileRuleRef[] FileRuleRef {
        get {
            return this.fileRuleRefField;
        }
        set {
            this.fileRuleRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Workaround {
        get {
            return this.workaroundField;
        }
        set {
            this.workaroundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class FileRuleRef {
    
    private string ruleIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RuleID {
        get {
            return this.ruleIDField;
        }
        set {
            this.ruleIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class FileAttribRef {
    
    private string ruleIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RuleID {
        get {
            return this.ruleIDField;
        }
        set {
            this.ruleIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class ExceptDenyRule {
    
    private string denyRuleIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DenyRuleID {
        get {
            return this.denyRuleIDField;
        }
        set {
            this.denyRuleIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class ExceptAllowRule {
    
    private string allowRuleIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AllowRuleID {
        get {
            return this.allowRuleIDField;
        }
        set {
            this.allowRuleIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class EKUs {
    
    private EKU[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EKU")]
    public EKU[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class EKU {
    
    private string idField;
    
    private byte[] valueField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class FileRules {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Allow", typeof(Allow))]
    [System.Xml.Serialization.XmlElementAttribute("Deny", typeof(Deny))]
    [System.Xml.Serialization.XmlElementAttribute("FileAttrib", typeof(FileAttrib))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Allow {
    
    private string idField;
    
    private string friendlyNameField;
    
    private string fileNameField;
    
    private string internalNameField;
    
    private string fileDescriptionField;
    
    private string productNameField;
    
    private string packageFamilyNameField;
    
    private string packageVersionField;
    
    private string minimumFileVersionField;
    
    private string maximumFileVersionField;
    
    private byte[] hashField;
    
    private string appIDsField;
    
    private string filePathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InternalName {
        get {
            return this.internalNameField;
        }
        set {
            this.internalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileDescription {
        get {
            return this.fileDescriptionField;
        }
        set {
            this.fileDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageFamilyName {
        get {
            return this.packageFamilyNameField;
        }
        set {
            this.packageFamilyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageVersion {
        get {
            return this.packageVersionField;
        }
        set {
            this.packageVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinimumFileVersion {
        get {
            return this.minimumFileVersionField;
        }
        set {
            this.minimumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaximumFileVersion {
        get {
            return this.maximumFileVersionField;
        }
        set {
            this.maximumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] Hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AppIDs {
        get {
            return this.appIDsField;
        }
        set {
            this.appIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FilePath {
        get {
            return this.filePathField;
        }
        set {
            this.filePathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Deny {
    
    private string idField;
    
    private string friendlyNameField;
    
    private string fileNameField;
    
    private string internalNameField;
    
    private string fileDescriptionField;
    
    private string productNameField;
    
    private string packageFamilyNameField;
    
    private string packageVersionField;
    
    private string minimumFileVersionField;
    
    private string maximumFileVersionField;
    
    private byte[] hashField;
    
    private string appIDsField;
    
    private string filePathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InternalName {
        get {
            return this.internalNameField;
        }
        set {
            this.internalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileDescription {
        get {
            return this.fileDescriptionField;
        }
        set {
            this.fileDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageFamilyName {
        get {
            return this.packageFamilyNameField;
        }
        set {
            this.packageFamilyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageVersion {
        get {
            return this.packageVersionField;
        }
        set {
            this.packageVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinimumFileVersion {
        get {
            return this.minimumFileVersionField;
        }
        set {
            this.minimumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaximumFileVersion {
        get {
            return this.maximumFileVersionField;
        }
        set {
            this.maximumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] Hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AppIDs {
        get {
            return this.appIDsField;
        }
        set {
            this.appIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FilePath {
        get {
            return this.filePathField;
        }
        set {
            this.filePathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class FileAttrib {
    
    private string idField;
    
    private string friendlyNameField;
    
    private string fileNameField;
    
    private string internalNameField;
    
    private string fileDescriptionField;
    
    private string productNameField;
    
    private string packageFamilyNameField;
    
    private string packageVersionField;
    
    private string minimumFileVersionField;
    
    private string maximumFileVersionField;
    
    private byte[] hashField;
    
    private string appIDsField;
    
    private string filePathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InternalName {
        get {
            return this.internalNameField;
        }
        set {
            this.internalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FileDescription {
        get {
            return this.fileDescriptionField;
        }
        set {
            this.fileDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageFamilyName {
        get {
            return this.packageFamilyNameField;
        }
        set {
            this.packageFamilyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PackageVersion {
        get {
            return this.packageVersionField;
        }
        set {
            this.packageVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MinimumFileVersion {
        get {
            return this.minimumFileVersionField;
        }
        set {
            this.minimumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaximumFileVersion {
        get {
            return this.maximumFileVersionField;
        }
        set {
            this.maximumFileVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="hexBinary")]
    public byte[] Hash {
        get {
            return this.hashField;
        }
        set {
            this.hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AppIDs {
        get {
            return this.appIDsField;
        }
        set {
            this.appIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FilePath {
        get {
            return this.filePathField;
        }
        set {
            this.filePathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class AllowedSigners {
    
    private AllowedSigner[] allowedSignerField;
    
    private string workaroundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowedSigner")]
    public AllowedSigner[] AllowedSigner {
        get {
            return this.allowedSignerField;
        }
        set {
            this.allowedSignerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Workaround {
        get {
            return this.workaroundField;
        }
        set {
            this.workaroundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class AllowedSigner {
    
    private ExceptDenyRule[] exceptDenyRuleField;
    
    private string signerIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExceptDenyRule")]
    public ExceptDenyRule[] ExceptDenyRule {
        get {
            return this.exceptDenyRuleField;
        }
        set {
            this.exceptDenyRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SignerId {
        get {
            return this.signerIdField;
        }
        set {
            this.signerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class DeniedSigners {
    
    private DeniedSigner[] deniedSignerField;
    
    private string workaroundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeniedSigner")]
    public DeniedSigner[] DeniedSigner {
        get {
            return this.deniedSignerField;
        }
        set {
            this.deniedSignerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Workaround {
        get {
            return this.workaroundField;
        }
        set {
            this.workaroundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class DeniedSigner {
    
    private ExceptAllowRule[] exceptAllowRuleField;
    
    private string signerIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExceptAllowRule")]
    public ExceptAllowRule[] ExceptAllowRule {
        get {
            return this.exceptAllowRuleField;
        }
        set {
            this.exceptAllowRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SignerId {
        get {
            return this.signerIdField;
        }
        set {
            this.signerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class UpdatePolicySigner {
    
    private string signerIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SignerId {
        get {
            return this.signerIdField;
        }
        set {
            this.signerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class UpdatePolicySigners {
    
    private UpdatePolicySigner[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UpdatePolicySigner")]
    public UpdatePolicySigner[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class SupplementalPolicySigner {
    
    private string signerIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SignerId {
        get {
            return this.signerIdField;
        }
        set {
            this.signerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class SupplementalPolicySigners {
    
    private SupplementalPolicySigner[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupplementalPolicySigner")]
    public SupplementalPolicySigner[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CiSigner {
    
    private string signerIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SignerId {
        get {
            return this.signerIdField;
        }
        set {
            this.signerIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class CiSigners {
    
    private CiSigner[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CiSigner")]
    public CiSigner[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Signers {
    
    private Signer[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Signer")]
    public Signer[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class Signer {
    
    private CertRoot certRootField;
    
    private CertEKU[] certEKUField;
    
    private CertIssuer certIssuerField;
    
    private CertPublisher certPublisherField;
    
    private CertOemID certOemIDField;
    
    private FileAttribRef[] fileAttribRefField;
    
    private string nameField;
    
    private string idField;
    
    private System.DateTime signTimeAfterField;
    
    private bool signTimeAfterFieldSpecified;
    
    /// <remarks/>
    public CertRoot CertRoot {
        get {
            return this.certRootField;
        }
        set {
            this.certRootField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CertEKU")]
    public CertEKU[] CertEKU {
        get {
            return this.certEKUField;
        }
        set {
            this.certEKUField = value;
        }
    }
    
    /// <remarks/>
    public CertIssuer CertIssuer {
        get {
            return this.certIssuerField;
        }
        set {
            this.certIssuerField = value;
        }
    }
    
    /// <remarks/>
    public CertPublisher CertPublisher {
        get {
            return this.certPublisherField;
        }
        set {
            this.certPublisherField = value;
        }
    }
    
    /// <remarks/>
    public CertOemID CertOemID {
        get {
            return this.certOemIDField;
        }
        set {
            this.certOemIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileAttribRef")]
    public FileAttribRef[] FileAttribRef {
        get {
            return this.fileAttribRefField;
        }
        set {
            this.fileAttribRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime SignTimeAfter {
        get {
            return this.signTimeAfterField;
        }
        set {
            this.signTimeAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SignTimeAfterSpecified {
        get {
            return this.signTimeAfterFieldSpecified;
        }
        set {
            this.signTimeAfterFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class SigningScenarios {
    
    private SigningScenario[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SigningScenario")]
    public SigningScenario[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class SigningScenario {
    
    private CiSigner[] productSignersField;
    
    private CiSigner[] testSignersField;
    
    private CiSigner[] testSigningSignersField;
    
    private string idField;
    
    private string friendlyNameField;
    
    private byte valueField;
    
    private string inheritedScenariosField;
    
    private HashAlgorithmType minimumHashAlgorithmField;
    
    private bool minimumHashAlgorithmFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CiSigner", IsNullable=false)]
    public CiSigner[] ProductSigners {
        get {
            return this.productSignersField;
        }
        set {
            this.productSignersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CiSigner", IsNullable=false)]
    public CiSigner[] TestSigners {
        get {
            return this.testSignersField;
        }
        set {
            this.testSignersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CiSigner", IsNullable=false)]
    public CiSigner[] TestSigningSigners {
        get {
            return this.testSigningSignersField;
        }
        set {
            this.testSigningSignersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string InheritedScenarios {
        get {
            return this.inheritedScenariosField;
        }
        set {
            this.inheritedScenariosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public HashAlgorithmType MinimumHashAlgorithm {
        get {
            return this.minimumHashAlgorithmField;
        }
        set {
            this.minimumHashAlgorithmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MinimumHashAlgorithmSpecified {
        get {
            return this.minimumHashAlgorithmFieldSpecified;
        }
        set {
            this.minimumHashAlgorithmFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum HashAlgorithmType {
    
    /// <remarks/>
    MD5,
    
    /// <remarks/>
    SHA1,
    
    /// <remarks/>
    SHA256,
    
    /// <remarks/>
    SHA384,
    
    /// <remarks/>
    SHA512,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:nt-example:sbpolicy")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:nt-example:sbpolicy", IsNullable=false)]
public partial class SbPolicy {
    
    private uint policyVersionField;
    
    private bool policyVersionFieldSpecified;
    
    private PolicyPublisherType policyPublisherField;
    
    private ulong deviceIDField;
    
    private RuleType[] rulesField;
    
    private EKU[] eKUsField;
    
    private Signer[] signersField;
    
    private SigningScenario[] signingScenariosField;
    
    private CiSigner[] ciSignersField;
    
    private BcdRule[] bcdRulesField;
    
    private Setting[] settingsField;
    
    private string friendlyNameField;
    
    /// <remarks/>
    public uint PolicyVersion {
        get {
            return this.policyVersionField;
        }
        set {
            this.policyVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PolicyVersionSpecified {
        get {
            return this.policyVersionFieldSpecified;
        }
        set {
            this.policyVersionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public PolicyPublisherType PolicyPublisher {
        get {
            return this.policyPublisherField;
        }
        set {
            this.policyPublisherField = value;
        }
    }
    
    /// <remarks/>
    public ulong DeviceID {
        get {
            return this.deviceIDField;
        }
        set {
            this.deviceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Rule", IsNullable=false)]
    public RuleType[] Rules {
        get {
            return this.rulesField;
        }
        set {
            this.rulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("EKU", IsNullable=false)]
    public EKU[] EKUs {
        get {
            return this.eKUsField;
        }
        set {
            this.eKUsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Signer", IsNullable=false)]
    public Signer[] Signers {
        get {
            return this.signersField;
        }
        set {
            this.signersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SigningScenario", IsNullable=false)]
    public SigningScenario[] SigningScenarios {
        get {
            return this.signingScenariosField;
        }
        set {
            this.signingScenariosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CiSigner", IsNullable=false)]
    public CiSigner[] CiSigners {
        get {
            return this.ciSignersField;
        }
        set {
            this.ciSignersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BcdRule", IsNullable=false)]
    public BcdRule[] BcdRules {
        get {
            return this.bcdRulesField;
        }
        set {
            this.bcdRulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable=false)]
    public Setting[] Settings {
        get {
            return this.settingsField;
        }
        set {
            this.settingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FriendlyName {
        get {
            return this.friendlyNameField;
        }
        set {
            this.friendlyNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:nt-example:sbpolicy")]
public enum PolicyPublisherType {
    
    /// <remarks/>
    Debug,
    
    /// <remarks/>
    PreProduction,
}
